title: "Sophia University | Precision Engineering Research Group | Yilmaz Lab"
description: "Assistant Professor | Tribology, Nucleate Boiling, Heat Transfer"
url: "https://fst.sophia.ac.jp/en/faculty/emir-yilmaz"
baseurl: ""  # leave this blank for user.github.io style sites

email: yilmaz@sophia.ac.jp
github_username: emiryilmaz  # replace with your GitHub username
google_scholar: ""  # insert your Google Scholar ID here
orcid_id: ""        # optional

# Social
twitter_username: ""  # optional
linkedin_username: "" # optional

# Academic info
institution: "Sophia University"
position: "Assistant Professor"
group: "Precision Engineering Research Group"
location: "Tokyo, Japan"

# Build settings
markdown: kramdown
theme: al-folio
